= Getting started

To get started with Antora, I recommend the following procedure:

. Make sure node/npm are installed. If that doesn't mean anything to you, follow:
+
https://docs.antora.org/antora/2.3/install/linux-requirements/

. Install Antora using the following guide:
+
https://docs.antora.org/antora/2.3/install/install-antora/

. Clone the demo repo
+
----
$ git clone https://gitlab.com/antora/demo/docs-site.git
----

. Run the xref:playbook.adoc[playbook]:
+
--
----
$ cd docs-site
$ antora antora-playbook.yml
----

This should create HTML output that you can view locally.
If you encounter issues, reach out on the https://chat.google.com/room/AAAAQ1o1BQY[chat room].

This repo does not contain any AsciiDoc files, instead it pulled the contents of the following repos:

* https://gitlab.com/antora/demo/demo-component-a
* https://gitlab.com/antora/demo/demo-component-b

Antora creates HTML from:

* the master branch of component A 
* the v2.0 and v1.0 branches of component B

Antora also pulls the content of the  https://gitlab.com/antora/antora-ui-default repo for the HTML styling that it uses to create the output.

Note that the AsciiDoc files are quite buried in the directory structure of the two component repos. 
For more information, see xref:content.adoc[].

--