:navtitle: Playbooks

= Antora playbooks

There is a lot of documentation about https://docs.antora.org/antora/2.3/playbook/[playbooks], but here are my notes:

Production playbooks:: Typically, a production playbook is used to publish HTML to a website and consists of:
+
--
* references to hosted git repos and tags/branches
* reference to a https://docs.antora.org/antora/2.3/playbook/ui-bundle-url/[UI] that determines the look and feel of the website.
--

Local or preview playbooks:: Typically, a local playbook references the currently saved files on the user's computer to create a preview of the site.
+
--
The content source syntax for a local playbook is:

----
  - url: ./
    branches: HEAD
----

A common misperception here is that HEAD refers to the latest commit, however, in this case, it refers to saved files, not necessarily staged or committed.

-- 


NOTE: Symlinks in repos might work with a local playbook, but are not supported when the playbook references repos, ie production playbooks.
